import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        'quanta': ['Quanta Grotesk', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'fluent': ['Fluent Font', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#593EFF",
          foreground: "#ECF2F9",
          50: "#F4F1FF",
          100: "#EBE4FF", 
          200: "#D9CCFF",
          300: "#C0A9FF",
          400: "#9D7AFF",
          500: "#593EFF",
          600: "#4E34E6",
          700: "#412BC2",
          800: "#36239E",
          900: "#2B1C7A",
        },
        secondary: {
          DEFAULT: "#140F2D",
          foreground: "#ECF2F9",
          50: "#F2F1F8",
          100: "#E8E6F2",
          200: "#D4CFE8",
          300: "#B8B0D9",
          400: "#9287C4",
          500: "#6B5AA8",
          600: "#4A3F7D",
          700: "#140F2D",
          800: "#0F0B26",
          900: "#0C091F",
        },
        accent: {
          DEFAULT: "#0DEF7C",
          foreground: "#201857",
          50: "#F0FEF6",
          100: "#DCFCE7",
          200: "#BBF7D0",
          300: "#86EFAC",
          400: "#4ADE80",
          500: "#0DEF7C",
          600: "#0BD968",
          700: "#0AB955",
          800: "#0A9944",
          900: "#087A37",
        },
        muted: {
          DEFAULT: "#ECF2F9",
          foreground: "#201857",
          50: "#FAFBFC",
          100: "#ECF2F9",
          200: "#E2E8F0",
          300: "#CBD5E1",
          400: "#94A3B8",
          500: "#64748B",
          600: "#475569",
          700: "#334155",
          800: "#1E293B",
          900: "#0F172A",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        caesoft: {
          purple: "#593EFF",
          navy: "#201857",
          green: "#0DEF7C",
          light: "#ECF2F9",
          'purple-light': "#7B5FFF",
          'purple-dark': "#3F2AE6",
          'navy-light': "#2A1F66",
          'navy-dark': "#161142",
          'green-light': "#2BF28A",
          'green-dark': "#09CC68",
          'light-darker': "#D8E4F1",
          'ultra-dark': "#080518",
          'deep-dark': "#0C091F",
          'card-dark': "#0F0B26",
          'section-dark': "#140F2D",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(50px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        rotate: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(89, 62, 255, 0.3)" },
          "50%": { boxShadow: "0 0 40px rgba(89, 62, 255, 0.6)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s ease-out",
        "slide-in-right": "slide-in-right 0.8s ease-out",
        rotate: "rotate 20s linear infinite",
        "pulse-glow": "pulse-glow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
